stages:
  - build
  - codestyle
  - test

# BUILD STAGES
build_cat:
  stage: build
  script:
    - cd src/C2_SimpleBashUtils/cat
    - make
  artifacts:
    paths:
      - src/C2_SimpleBashUtils/cat/s21_cat
    expire_in: 30 days

build_grep:
  stage: build
  script:
    - cd src/C2_SimpleBashUtils/grep
    - make
  artifacts:
    paths:
      - src/C2_SimpleBashUtils/grep/s21_grep
    expire_in: 30 days

# CODESTYLE STAGE
codestyle:
  stage: codestyle
  script:
    - clang-format -n --style=Google src/C2_SimpleBashUtils/**/*.{c,h}
  allow_failure: false

# TEST STAGES
test_cat:
  stage: test
  script:
    - cd src/C2_SimpleBashUtils/cat
    - bash tests.sh
  dependencies:
    - build_cat
    - codestyle
  allow_failure: false

test_grep:
  stage: test
  script:
    - cd src/C2_SimpleBashUtils/grep
    - bash tests.sh
  dependencies:
    - build_grep
    - codestyle
  allow_failure: false
