stages:
  - build
  - codestyle
  - test
  - deploy

# BUILD STAGES
build_cat:
  stage: build
  script:
    - cd src/C2_SimpleBashUtils/cat1
    - make
  after_script:
    - bash src/telegram.sh
  artifacts:
    paths:
      - src/C2_SimpleBashUtils/cat/s21_cat
    expire_in: 30 days

build_grep:
  stage: build
  script:
    - cd src/C2_SimpleBashUtils/grep
    - make
  after_script:
    - bash src/telegram.sh
  artifacts:
    paths:
      - src/C2_SimpleBashUtils/grep/s21_grep
    expire_in: 30 days

# CODESTYLE STAGE
codestyle:
  stage: codestyle
  script:
    - clang-format -n --Werror --style=Google src/C2_SimpleBashUtils/**/*.{c,h}
  after_script:
    - bash src/telegram.sh
  rules:
    - when: always
  needs: []

# TEST STAGES
test_cat:
  stage: test
  script:
    - cd src/C2_SimpleBashUtils/cat
    - bash tests.sh
  after_script:
    - bash src/telegram.sh
  dependencies:
    - build_cat

test_grep:
  stage: test
  script:
    - cd src/C2_SimpleBashUtils/grep
    - bash tests.sh
  after_script:
    - bash src/telegram.sh
  dependencies:
    - build_grep

# DEPLOY STAGE
deploy:
  stage: deploy
  script:
    - scp src/C2_SimpleBashUtils/cat/s21_cat seb@192.168.88.140:/usr/local/bin
    - scp src/C2_SimpleBashUtils/grep/s21_grep seb@192.168.88.140:/usr/local/bin
  after_script:
    - bash src/telegram.sh
  dependencies:
    - build_cat
    - build_grep
    - codestyle
    - test_cat
    - test_grep
  when: manual
  allow_failure: false
